### ISSUE TITLE
Request for CSS selector performance blog case study files

### ISSUE THREAD

**Issue by qwertyvipul** [MicrosoftEdge/DevTools#124]
I came across [this interesting blog](https://blogs.windows.com/msedgedev/2023/01/17/the-truth-about-css-selector-performance/) about CSS selector performance. Would it possible for the team to provide the files and the code for the case study included in the blog? In fact, it would be great if you could publish it somewhere on GitHub and link the case study in the blog to it.

**Comment by captainbrosset** [comment]
Thanks for asking. I wrote the article, and made the demo. I hesitated to publish the demo files because it's very easy to get widely different results than the ones I showed in the article. It all depends on the test machine.
But I think it makes sense to publish them anyway. I'll add them to the https://github.com/MicrosoftEdge/Demos repo soon.

**Comment by qwertyvipul** [comment]
Yes, widely different results is and should be expected, however it would be helpful for trying things out by oneself.

**Comment by captainbrosset** [comment]
I agree. I have this on my list of things to do soon, hopefully :)

**Comment by captainbrosset** [comment]
There you go: https://microsoftedge.github.io/Demos/photo-gallery/

**Comment by qwertyvipul** [comment]
Yay! Thanks :grinning:
