### ISSUE TITLE
Bring Back The Old Devtool In Stable Edge 120

### ISSUE THREAD

**Issue by edwin-egalite** [MicrosoftEdge/DevTools#208]
I noticed that the new "Focus" devtool which was available in Canary has became the default devtool in stable Edge since version 120. Previously I was able to bring back the old devtool in canary by turning off the "Focus" option in setting. But this option is not available in stable Edge.

How do I bring back the old devtool UI in stable Edge?

The huge annoyance I have with the new devtool UI is that I couldn't drag the top to adjust the height easily. I have to drag exactly the very top edge in order to do so.

![image](https://github.com/MicrosoftEdge/DevTools/assets/10771300/b356b748-9e9b-4268-9742-bd98f37a5808)

Furthermore, the Quick View panel reappear every time I open the devtool even if I toggle it off previously. To me, the new devtool UI is half baked and it's not ready.

**Comment by captainbrosset** [comment]
Thank you for this feedback. I'll make sure to track these two bugs so that our team can fix them as quickly as possible.

We took our time to test this feature in Canary for a long period specifically to get this kind of feedback and address the issues before rolling out in Release. Thanks to this, we addressed many issues already. But these two bugs just didn't come up.

In the meantime, you can go back to the legacy UI:

* In DevTools, press <kbd>F1</kbd>.
* Select the **Switch back to the legacy DevTools UI** box.
* Restart DevTools.

**Comment by edwin-egalite** [comment]
Wow, thanks. This really save my life. I actually gave up and installed Chrome instead to get the old UI.

Thank you so much for the info. Now I can remove Chrome from my machine 😁
