### ISSUE TITLE
Selector Stats tab doesn't exist in my Performance panel

### ISSUE THREAD

**Issue by SuperOleg39** [MicrosoftEdge/DevTools#223]
Hello!

My configuration:
- MS Edge 121.0.2277.106
- MacOS Ventura 13.5

Try to debug CSS selectors performance by https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/evaluate-performance/selector-stats guide.

Selector Stats tab doesn't exist when I select Style Recalculation block :(

<img width="1066" alt="Снимок экрана 2024-02-06 в 13 24 03" src="https://github.com/MicrosoftEdge/DevTools/assets/15360667/d46ea94c-5cbb-4dae-9e58-7b71a9256be8">

**Comment by captainbrosset** [comment]
Thank you for filing, and sorry about this. This is a bug that we've been tracking for some time already and we have a fix for it. In fact, if you try in Edge Canary, the bug should already be fixed there.

@bwalderman could you please let us know which version of Edge did this get fixed with, and when will the fix become available in Edge Release? Thanks.
