### ISSUE TITLE
YouTube Livestream chat load super slow on Edge

### ISSUE THREAD

**Issue by quyenvsp** [MicrosoftEdge/DevTools#256]
This problem happened about 2 months ago. Work fine on other browser like Firefox, Chrome

1, go to any youtube live stream
2, open Live chat panel by click `Show chat` button

It load super slow and do not show any chat message, check network tab will see immediately 3 same request to
 `https://www.youtube.com/live_chat?continuation=...` with Pending status, after 20 seconds it changed to Error and Live chat panel work now. Copy curl one of 3 above call with postman will immediately get result instead of delay 20 seconds.

Can fix by block Youtube servier worker
```
1, adblock filter ||www.youtube.com/sw.js

2, open youtube, press F12 (right click > inspect), go to Application tab

3, click Service workers to see list, click Unregister

Done.
```

Not sure it is Youtube or Edge problem but other browser working fine.

**Comment by captainbrosset** [comment]
Thanks for reaching out, and sorry that you're experiencing this issue.
However, this repository is specific to DevTools, not to the way that Edge connects to and downloads from YouTube or other sites. 
In order to send this feedback to the right teams, could you please send it again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.

**Comment by Redee** [comment]
same problem - veeeeeeeeeery slow open youtube livestream chat
ms edge version 136.0.3240.64

**Comment by giladfrid009** [comment]
+1 on that.

**Comment by huanth** [comment]
I'm having the same problem.

**Comment by yorkyang2333** [comment]
+1 Still not fixed in 2026
