### ISSUE TITLE
Edge no long working properly

### ISSUE THREAD

**Issue by nahdoogie** [MicrosoftEdge/DevTools#29]
Edge Dev, and Edge no longer working correctly when trying to do an Alteryx Replace Workflow.
It used to work several versions of edge back.  I've had to revert to using Chrome to do this 30 second process.
What I don't know if it's a setting issue or something internal in the Edge/EdgeDev code.
Can you assign someone to work with me on this issue?  Thanks  Neill

**Comment by captainbrosset** [comment]
Hi Neil, thanks for reaching out with this feedback. We'd love to help, but this isn't the best place for this particular feedback.
This repository is about the built-in Edge DevTools (also known as F12), not about the browser itself, and compatibility problems that might affect certain sites, like Alteryx.

In order to get help with this, could you please do the following:

* Go to the `...` menu (top-right corner of the browser)
* Then `Help and feedback`
* Then go to `Send feedback`
* A popup window will appear where you can describe your issue in details, and even provide screenshots of the problem. I also highly suggest providing as much info as you can. This will help the browser team investigate and hopefully resolve the issue. For example: what were you doing when the problem occurred? What happened, and what should have happened instead? Any error messages appeared anywhere? That sort of stuff really helps.

Thanks!
