### ISSUE TITLE
Some extensions don't work when resuming from background in Edge for Android

### ISSUE THREAD

**Issue by tesmite** [MicrosoftEdge/DevTools#290]
Some extensions (probably Manifest v2), such as uBlock origin and Tampermonkey, are disabled and do not work when Edge for Android resumes from background.
In older versions around 125-129, this worked by disabling and re-enabling the extension on the extensions page, but in the current Edge Canary 132, the app crashes when you try to open the extensions page, so this is clearly a bug.
I found a tweet in Japanese that mentioned this bug. It seems that this bug occurs when returning by onPause() and onResume(), but not onRestart().
https://x.com/hole_orig/status/1850056908864094648
https://x.com/hole_orig/status/1853774353219125621

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Update the bug report template to include information about the Android extension disable issue when resuming from background.

I also created pull request: https://github.com/MicrosoftEdge/DevTools/pull/291


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by leahmsft** [comment]
Thank you for reporting this bug, but this isn't related to Edge DevTools. To get your feedback to the right team, go to **Settings and more > Help and feedback** to submit your feedback.

**Comment by tesmite** [comment]
I mistakenly thought it was a bug report page for Edge itself.
I'm sorry.
