### ISSUE TITLE
DevTools tools mostly appear blank extend with page won't refresh .

### ISSUE THREAD

**Issue by captainAmerica700** [MicrosoftEdge/DevTools#300]
one of the user of edge browser on latest version which is Version 131.0.2903.70 (Official build) (64-bit) with the previously mentioned  issue  the page refresh is also don't work at the time  when every thing is freeze check this also.

**Comment by leahmsft** [comment]
Hi @captainAmerica700, I suspect this is related to a known issue we're tracking here: https://github.com/MicrosoftEdge/DevTools/issues/296. The team is working on a fix that will land soon this week. 

Thanks for reporting this issue. Closing since we're already tracking it in https://github.com/MicrosoftEdge/DevTools/issues/296
