### ISSUE TITLE
New dev tools 102 cannot have console and source code displayed at same time

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [MicrosoftEdge/DevTools#64]
It is very important to use both while debugging. Not having this ability is a completely broken experience.

**Comment by captainbrosset** [comment]
Thanks for reporting this @zhangyiatmicrosoft. This functionality has not been removed from DevTools. So you might be having a bug that we need to fix.

Just to double check, could you please explain the steps you took to have both the code and console side by side? I want to understand exactly what you did in order to reproduce it locally and attempt to find a fix.

Also, it would be helpful if you could please provide a screenshot.

**Comment by zhangyiatmicrosoft** [comment]
In previous experience, when on Source tab, anytime can press ESC key to show console and work on source code and console at same time.

I switched back forgot how to get to the new UX at this moment -- but vividly remember the above operation was not successful, which is a major reason that I had to switch back.

**Comment by captainbrosset** [comment]
Thanks for the additional information. Could you please explain to me what "switch back" means in this context though?
What did you switch back to?

Are you referring to the new "Focus Mode" UI of DevTools (the one with the icons for the tools and the vertical activity bar)?
If that's what you mean, then the ESC key should still work. I just tried now in 102, with both Focus Mode on and off, and the ESC key worked for me. It toggles the bottom part of the tools (previously called the "drawer", and now called "quick view").

Now, one thing that may be at play here is that the bottom part can contain any tool. Not only the Console. Could it be that ESC worked for you, but was showing a different tool?

**Comment by zhangyiatmicrosoft** [comment]
yes your are right. No repro
