### ISSUE TITLE
ctrl+shift+f does not put focus in search box

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [MicrosoftEdge/DevTools#65]
Open dev tool, source code tab.
Ctrl+shift+F and start typing.
Notice everything goes to source code, not the search box.
You need an extra mouse click in search box.

(Compared to Chrome, this experience is unexpected and broken)

AB#39916722

**Comment by captainbrosset** [comment]
Great find! Thank you for reporting this. This is definitely a bug, and a regression too. I'll add it to the team's backlog so they can fix it soon.

**Comment by hxlnt** [comment]
@zhangyiatmicrosoft I was able to confirm that this bug fix has landed in Edge version 105.0.1308.0 (today's Canary). I would expect it to be a few weeks still until this change rolls out to Edge Stable. I will leave this issue open a bit longer while we monitor that the fix is on track for a release in Edge 105.

**Comment by captainbrosset** [comment]
We can close this bug now. The fix has been released with Edge 105 and I just validated that it works as expected now.
