### ISSUE TITLE
[feedback] Command Palette experiment

### ISSUE THREAD

**Issue by captainbrosset** [MicrosoftEdge/DevTools#73]
This issue is meant to collect feedback about the **Edge Command Palette** experiment.

Edge Command Palette is a new experiment that makes it possible to run useful productivity and developer commands in Edge by pressing `Ctrl+Q`. This includes running DevTools commands without having to open DevTools first. Learn more about this experiment and how to use it [from the documentation](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/edge-command-palette).

If you used Edge Command Palette and have any feedback about it, please leave a comment in this issue.

**Shortcut note:** the experiment started with the `Ctrl+Shift+Space` shortcut and that shortcut works in Microsoft Edge 105 to 107. Based on feedback received in this issue, it was changed to `Ctrl+Q` and this shortcut can be used starting with Microsoft Edge 108.

**Comment by codepo8** [comment]
One of the things I am missing is direct interaction. You can open DevTools from it and use some of the functionaliity there but often I don't want to do that. I'd love to see some immediate toggles being available through the command palette:

* Turn JavaScript on/off
* Switch dark/light mode of the current page (this is part of the rendering tool)
* Take full page screenshot (this is available as cmd+shift+s but people may not know it)
* Show/hide keyboard order (this is part of the accessibility panel)

**Comment by raekul** [comment]
Saw and tried out, found some issues.

Machine     SurfaceBook 2
Edition        Windows 11 Enterprise
OS build	   22000.739
Edge (beta) Version 104.0.1293.14

1. (with dark mode) Loading the palette each time, palette flashes in **light mode** then loads in the correct theme
2. (with dark mode) Similar to the above, when typing out queries, when suggestions enter/leave, they sometimes can cause individual suggestions or the entire suggestions panel to re-render in what looks like "light mode" then back to the theme.
3. Suggestions and or input field get cut off in certain cases (see screenshot below) 
   - _Second screenshot is upon navigating into the suggestions with arrow keys_
4. Typing can feel a bit sluggish and un-responsive, at times, it's minimal, but I would expect perhaps a slight delay on the suggestions instead of typing 🙂

![image for item 3 above](https://user-images.githubusercontent.com/4473269/178253124-f63efa27-4589-4b7b-ad38-84fe5cdc035f.png)

![second image for item 3 above](https://user-images.githubusercontent.com/4473269/178253468-c1c2cea7-3280-4ac7-b4bf-115ef4b22b7e.png)

**Comment by ngaitonde** [comment]
@raekul the work to make this UI accessible to Screen Readers is planned for us. Thank you for trying out the feature and providing your feedback.

**Comment by whl83111** [comment]
The shortcut `Ctrl+Shift+Space` is conflicted with macOS's change input method shortcut (`Ctrl+Space`), and won't work until I change the input method shortcut.

**Comment by codepo8** [comment]
> The shortcut `Ctrl+Shift+Space` is conflicted with macOS's change input method shortcut (`Ctrl+Space`), and won't work until I change the input method shortcut.

How does that work? I am a MacOS user and never triggered that. Do you need an external keyboard?

**Comment by whl83111** [comment]
> > The shortcut `Ctrl+Shift+Space` is conflicted with macOS's change input method shortcut (`Ctrl+Space`), and won't work until I change the input method shortcut.
> 
> How does that work? I am a MacOS user and never triggered that. Do you need an external keyboard?

Yes, I'm using an external keyboard, but I also tried the macbook built-in keyboard, doesn't work either.

Here are the versions:
macOS 12.4
edge 105.0.1321.0

**Comment by bradleypatton** [comment]
The shortcut  `Ctrl+Shift+Space` is not working on my desktop (Windows 11) either in Edge dev or release. Not sure if another app is capturing it. I do have Power Toys installed but it doesn't seem to trigger anything when I press that combination. Is there a way to alter the key combo or see what is capturing that combo?

**Comment by codepo8** [comment]
> The shortcut `Ctrl+Shift+Space` is not working on my desktop (Windows 11) either in Edge dev or release. Not sure if another app is capturing it. I do have Power Toys installed but it doesn't seem to trigger anything when I press that combination. Is there a way to alter the key combo or see what is capturing that combo?

This is currently only enabled in Canary, not in Dev yet.

**Comment by danieltharris** [comment]
I’d like to suggest the shortcut being changed to Ctrl + Shift + P so that it matches tooling such as VS Code and Windows Terminal. 
 
I feel like it would just make sense to keep them similar, especially since it's mainly power users / developers who will use the feature and they're already used to that shortcut.

**Comment by pixiekat** [comment]
Just enabled it and it works great, the only thing I noticed is that when first set up, it conflicts with the standard 1Password Quick Actions shortcut so I had to disable that first before I could use it. 

Also adding the ability to take a full page screenshot would be great.

**Comment by codepo8** [comment]
> Just enabled it and it works great, the only thing I noticed is that when first set up, it conflicts with the standard 1Password Quick Actions shortcut so I had to disable that first before I could use it.
> 
> Also adding the ability to take a full page screenshot would be great.

Thanks so much for your feedback. Good catch with the 1Password extension - I guess it is tough to find any keyboard shortcut that isn't used yet. 

As for the full page screenshot, I suppose you mean one that also scrolls the whole document, right?

This is already in device mode, so it should be easy to add.

<img width="336" alt="menu item in device mode offering full screen screenshot" src="https://user-images.githubusercontent.com/13508/182646348-16680550-07ac-4f67-a3bd-b22b0ba3820e.png">

**Comment by Nova38** [comment]
I am having the same issue with the onepass extension. Is there a way to remap the edge keyboard shortcut to a different shortcut of the users choice?

**Comment by WebMechanic** [comment]
speaking of screenshots... size (height) is limited to 16384px (also in Chrome)

i.e. try full page screenshot of https://css3test.com/
works in FF though

**Comment by WebMechanic** [comment]
> @Nova38 Is there a way to remap the edge keyboard shortcut to a different shortcut of the users choice?

try edge://extensions/shortcuts

**Comment by codepo8** [comment]
> speaking of screenshots... size (height) is limited to 16384px (also in Chrome)
> 
> i.e. try full page screenshot of https://css3test.com/ works in FF though

Interesting, I will file a bug and see why this is.

**Comment by Nova38** [comment]
> > @Nova38 Is there a way to remap the edge keyboard shortcut to a different shortcut of the users choice?
> 
> try edge://extensions/shortcuts

That is only for extensions not for edge shortcuts.

**Comment by WebMechanic** [comment]
> That is only for extensions not for edge shortcuts.

yes, I thought you might try to change the shortcutss of the onepass extension

**Comment by Nova38** [comment]
> > That is only for extensions not for edge shortcuts.
> 
> yes, I thought you might try to change the shortcutss of the onepass extension

Ah okay, that shortcut is actually also for the system wide onepass program that integrates with the extension. I would really prefer not to change that as i have been using it for years and it is very convenient. It registers the hotkey globally.

**Comment by erdraud** [comment]
@WebMechanic @Nova38 @pixiekat we will be updating the keyboard shortcut, thank you for your feedback!

**Comment by captainbrosset** [comment]
The description at the top of this issue, and the documentation were both updated with the new `Ctrl+Q` shortcut that can be used starting with Microsoft Edge 108.

**Comment by pauljacobson** [comment]
I love this feature in a browser. Vivaldi has a really nice implementation of this sort of feature that I would love to see expanded in Microsoft Edge. 

One option I use constantly is the ability to use the command palette to close tabs to the right of my active tab. This seems like a small thing, but it's a huge quality of life feature for me. Here's an example in Vivaldi:


https://user-images.githubusercontent.com/2912202/198965713-b273a0e7-a28d-4b89-a8bb-2efbf5e6b7f4.mp4

Even if the Edge version doesn't explicitly support this option, I'd love to be able to define custom commands and select options like closing tabs to the right of an active tab.

**Comment by chrishutchinson** [comment]
Excited about this, lots of potential. 

I am keen to add a command palette to my own product, but if we're heading towards a browser standard palette with a global shortcut (a la GitHub and Slack) then I'd rather be able to re-use the native one rather than implement my own in-app one, and register commands from my code (via the `manifest.json` maybe?) that can appear in the palette. Maybe the `>` prefix or similar could quick filter to app-specific commands.

**Comment by ankitbko** [comment]
One suggestion is to have capability to "Search Tabs" through Command Palette itself instead of having another shortcut for it. Result can be displayed similar to how historical tab search result is displayed.
![image](https://user-images.githubusercontent.com/3169316/203471555-e7e00de3-42d2-476f-9a9f-f2a3536ee2ba.png)

**Comment by captainbrosset** [comment]
> One suggestion is to have capability to "Search Tabs" through Command Palette itself instead of having another shortcut for it. Result can be displayed similar to how historical tab search result is displayed.

I agree, having this directly in command palette, instead of having to switch the tab search window, would be a nicer experience.

**Comment by familyFlyss** [comment]
VM66

**Comment by lisp719** [comment]
If the mouse cursor hovers over the command palette while entering text, it will focus.
I would prefer that text input be the preferred method.

**Comment by nathollings** [comment]
The ability to change the shortcut would be great. 

VsCode has ctrl + p for files and ctrl + shift + p for tools. something like this would be great.

**Comment by WebMechanic** [comment]
I wouldn't want `ctrl + p` in the browser window taken over by a feature I probably wouldn't use that often (no matter how useful it seems) as it's been assigned to "Print" since ever and in virtually every application on all systems that access printers.
There are likely as many people that like to "print" (to pdf) and thus want "ctrl+p" to do just that as there are nerds and geeks and self acclaimed power users that like to use it to open a devtools/vscode-like Command Palette and go from there (which always requires two or more steps to perform the most simple task/command).

Different users have different needs, and nobody here is **THE** ultimate reference user for any app whatsover, so by all means Microsoft: **make this shortcut customizable** so users can pick whatever they want according to _their priority_ and let's not get into a futile discussion which shortcut is good or not or preferred by anyone.

_Once_ a Command Palette is available I'm confident it can be stuffed with a sorts of features bit by bit 'cos unlike menu items and toolbar buttons it doesn't take any more screen estate to do so.

These _features_ sound interesting to have, their proposed shortcut: not so much :)
> - showed the all the tabs in order of recently used
> - close all tab

Have a nice time.

**Comment by martinjanocko** [comment]
Hello, the `CTRL + Q` shortcut interferes with Outlook web app. Previously you could toggle emails being read/unread and now that's unusable in Edge.

**Comment by captainbrosset** [comment]
Thanks @martinjanocko, for reporting this. Does Ctrl+U works to mark emails as unread? And, what does Ctrl+Q do? Nothing? Open the Command Palette?

I'm asking because it seems to be working for me still. In any tab other than Outlook, Ctrl+Q opens the Command Palette, and in Outlook Ctrl+U and Ctrl+Q mark emails as unread/read without Command Palette interference.

Any extra detail you can share would help us understand the issue and therefore investigate it.

**Comment by martinjanocko** [comment]
Since yesterday I had the command palette feature disabled in `edge://flags/`, but now when I wanted to test it again to be able to reply and enabled it, the `CTRL + Q` works as expected in OWA. So all good on my side, probably a temporary issue after MS Edge update not really sure what has happened. Sorry for the troubles.

**Comment by captainbrosset** [comment]
Closing this issue. Thank you all for the feedback you have shared here while the issue was open. It helped us a lot work on this experiment.

**Comment by jaskp** [comment]
Is this feature gone? Ctrl+Q doesn't do anything for me on 123.0.2420.51 beta macOS and I can't find the flag in edge://flags anymore either. It's also missing from 124 canary but is still present in 122 stable.

**Comment by captainbrosset** [comment]
Correct, we're removing this experimental feature starting with Microsoft Edge 123. A release note, which mentions this, will be published later today.

**Comment by pixiekat** [comment]
Aw, I'm sad to hear this but I know something better will come along with the feedback gathered!

**Comment by Relin404** [comment]
This was really one of the top-notch features that made Edge my main browser for a long time. I really hate that it's gone, and I can't see a reason for its demise.

**Comment by captainbrosset** [comment]
@Relin404 this experiment had never made it out of experimental mode, and our team doesn't have capacity to maintain it over time.
I'm curious though, which commands did you used most with it? If what you used most were DevTools commands, you can access them from within DevTools directly by using the Command Menu (Ctrl+Shift+P).
