### ISSUE TITLE
bug in computed tab at the styles section

### ISSUE THREAD

**Issue by princemuel** [MicrosoftEdge/DevTools#88]
![dev-tools](https://user-images.githubusercontent.com/68931805/183796810-3fc9afae-4679-42b5-93ee-ac66e4752ba7.png)

Hi. There's an issue in the computed tab at the styles section where some of the text is not rendered properly, not scrollable or is hidden.

Browser Name: Microsoft Edge
Browser Version: 104.0.1293.47 (Official build) (64-bit)

**Comment by captainbrosset** [comment]
Thanks for filing this issue. I am able to reproduce the bug in the current stable version fo Edge (104).
However, I just tested this 105 and 106, and the bug is fixed there. So, I'll close this issue now. If you can test with 105 and confirm, that'd be great. It should get released on October 9th, which is less than a month away.
